[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.81.0"

[context.deploy-preview.environment]
HUGO_VERSION = "0.81.0"

[context.branch-deploy.environment]
HUGO_VERSION = "0.81.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
